### ISSUE TITLE
Read Stream from ANOTHER Raspberry Pi with motion installed

### ISSUE THREAD

**Issue by sroettgermann** [45clouds/homebridge-ip-camera#12]
Hello!

Is there any experience regarding my thread title? I want to read the video stream from another RPi where I have installed motion and a USB webcam. 
The Stream is working on http://RPI-IPADDRESS:8081 but Home won't be able to enable the camera.

**Comment by 45clouds** [comment]
Are you sure that the stream is working? Can you please use VLC and open the stream using this app. The address should rstp://rpi-address:8081 in your case.

**Comment by 45clouds** [comment]
Sorry... my mistake. Correct link is:

rtsp://user_if_any:password_if_any@192.168.1.24:8081

or better

rtsp://user_if_any:password_if_any@rpi-address:554

because rtsp stream uses port 554 (tcp/udp) by default.

**Comment by sroettgermann** [comment]
Okay. I made it to work with the http address. But the question is, can I devide between video and still-image source somewhere?

**Comment by 45clouds** [comment]
Can you explain what do you want to achieve? :)

**Comment by sroettgermann** [comment]
homebridge-ip-camera has different options for source and still-image-source. Maybe I don't understand it correctly, but in my opinion there should be an address for still images and one for video image source?! Right?

**Comment by 45clouds** [comment]
Yes. That's right. For example I use HikVision cameras and they offer rtsp stream and still-image source (screenshots). They have different URL's inside camera. That's why I use:

                    "source": "-re -i rtsp://ip_address:554/Streaming/Channels/101",
                    "stillImageSource": "-i http://ip_address:80/Streaming/channels/1/picture",

in my configuration file.

**Comment by sroettgermann** [comment]
Okay, thank you!
