### ISSUE TITLE
Where do I get this parameter

### ISSUE THREAD

**Issue by marcotini** [45clouds/homebridge-ip-camera#2]
If I use an original [camera module](https://www.raspberrypi.org/products/camera-module/) from Raspberry Pi, where do I get this path? 

```
"source": "-re -i rtsp://10.0.19.10:554/Streaming/Channels/101",
"stillImageSource": "-i http://10.0.19.10/Streaming/channels/101/picture",
```

I just follow [this](https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian) to install the right version.

**Comment by himichaelroberts** [comment]
If you're using MotionEye you can find the urls under Settings - Video Stream.

**Comment by marcotini** [comment]
Yes _http_ ok but not _rtsp_.

**Comment by 45clouds** [comment]
Hi,

My home bridge add-on requires rtsp stream to work. You can work with PI camera if you create rtsp server which will produce this stream. You can look at these instructions:

https://forum.synology.com/enu/viewtopic.php?t=98870

I'm afraid that PI doesn't have enough power to create and decode rtsp stream at the same time.

Regards,
Michal
