### ISSUE TITLE
Stream on homekit low resolution

### ISSUE THREAD

**Issue by sorriso93** [45clouds/homebridge-ip-camera#27]
Hello
I get from the log this:

Converting to HomeKit
-re -f mjpeg -i http://192.168.0.11 -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 10 -f rawvideo -tune zerolatency -vf scale=640:360 -b:v 132k -bufsize 132k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params MrESuqNnX7Omz5m7w6O87KP1SELh7Kwd8jjQ5CbJ srtp://192.168.0.70:55202?rtcpport=55202&localrtcpport=55202&pkt_size=1378

but I configured the maxwidth and maxheight as my webcam provides on httt page

{
                    "name": "CAMCUCINA3",
                    "videoConfig": {
                        "source": "-re -f mjpeg -i http://192.168.0.11",
                        "stillImageSource": "-f mjpeg -i http://192.168.0.11",
                        "maxStreams": 2,
                        "maxWidth": 1024,
                        "maxHeight": 768,
                        "maxFPS": 10
                    }
                },

Is it homekit requiring the stream at 640x360?
many thanks

**Comment by 45clouds** [comment]
No. You can use resolution which is supported by your camera. In fact I don't know what kind of camera you have, but please check https://www.ispyconnect.com/sources.aspx for correct url for your camera.

stillImageSource should point to url with jpeg (not mjpeg)
source should point to url with rtp stream

**Comment by sorriso93** [comment]
Hello
it is an arduino camera (esp32cam). I will try with a sketch with rtsp
th
