### ISSUE TITLE
Adding Second Camera

### ISSUE THREAD

**Issue by simonrb2000** [45clouds/homebridge-ip-camera#4]
Hi,

Trying to add a second camera to the config file, can't seem to get it right? Any ideas on the format? Cheers

**Comment by simonrb2000** [comment]
Sorted

**Comment by theo-69** [comment]
@simonrb2000 how did you sort it?

**Comment by simonrb2000** [comment]
I just added it underneath the first camera as another accessory I think..

**Comment by 45clouds** [comment]
Working example below:

            "platform": "Camera-ffmpeg",
            "cameras": [
              {
                "name": "FRONT",
                "videoConfig": {
                    "source": "-re -i rtsp://user:password@10.12.9.211:554/Streaming/Channels/101",
                    "stillImageSource": "-i http://user:password@10.12.9.211/Streaming/channels/1/picture",
                    "maxStreams": 2,
                    "maxWidth": 1280,
                    "maxHeight": 720,
                    "maxFPS": 10
                 }
              },
              {
                "name": "GARAGE",
                "videoConfig": {
                    "source": "-re -i rtsp://user:password@10.12.9.212:554/Streaming/Channels/101",
                    "stillImageSource": "-i http://user:password@10.12.9.212/Streaming/channels/1/picture",
                    "maxStreams": 2,
                    "maxWidth": 1280,
                    "maxHeight": 720,
                    "maxFPS": 10
                 }
              }
             ]

**Comment by theo-69** [comment]
Thanks its working
